// app/layout.tsx
import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'
import './globals.css'
import {NextIntlClientProvider} from "next-intl";
import {ThemeProvider} from "next-themes";
import {getLocale, getMessages} from "next-intl/server";
import {AppSessionProvider} from '@/components/auth/session-provider'

const geistSans = Geist({variable: '--font-geist-sans', subsets: ['latin']})
const geistMono = Geist_Mono({variable: '--font-geist-mono', subsets: ['latin']})

export const metadata: Metadata = {
  title: 'MKT Proxy',
  description: 'Generated by create next app'
}

export default async function RootLayout({children}: { children: React.ReactNode }) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html suppressHydrationWarning>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <NextIntlClientProvider locale={locale} messages={messages}>
      <AppSessionProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </AppSessionProvider>
    </NextIntlClientProvider>

    </body>
    </html>
  )
}
